### ISSUE TITLE
docker-compose up -d error

### ISSUE THREAD

**Issue by lk3687051** [tgbot-collection/SearchGram#118]
bot_1         | Traceback (most recent call last):
bot_1         |   File "/SearchGram/searchgram/bot.py", line 18, in <module>
bot_1         |     from searchgram import SearchEngine
bot_1         | ModuleNotFoundError: No module named 'searchgram'
searchgram_bot_1 exited with code 1
client_1      | Traceback (most recent call last):
client_1      |   File "/SearchGram/searchgram/client.py", line 21, in <module>
client_1      |     from searchgram import SearchEngine

**Comment by BennyThink** [comment]
Fixed now!
