### ISSUE TITLE
about the sync history message

### ISSUE THREAD

**Issue by ZhiShengYuan** [tgbot-collection/SearchGram#119]
When I attempt to synchronize message history, it notifies me with the error `pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet` . This issue occurs towards the end of syncing for certain accounts. I suspect that the program may not handle the conclusion of the message syncing process properly.

**Comment by BennyThink** [comment]
> It is recommended to use usernames whenever possible when configuring the sync ID

https://github.com/tgbot-collection/SearchGram/blob/master/Docker.md#6-optionalsetup-sync-id
