### ISSUE TITLE
部分群组没有跳转链接

### ISSUE THREAD

**Issue by Astlm** [tgbot-collection/SearchGram#122]
![Screenshot_2024-02-04-11-55-09-866_org telegram plus](https://github.com/tgbot-collection/SearchGram/assets/106404630/0de1744c-8e76-4ead-a2d8-b3bc4cce8b1b)
如图
另外希望早日把bot的消息跳转安排上吧
通过
tg://openmessage?user_id="机器人id或用户id"&message_id="消息id"
https://t.me/c/"频道id或群组id"/"消息id"
跳转消息还是太麻烦了

**Comment by BennyThink** [comment]
啊可能你的群没有用户名，所以就没有。我加上了 `tg://user?id={from_id}` 不知道是否可用

跳转消息似乎不可用，不过也加上了，可能是Android限定
