### ISSUE TITLE
关于Sync ID的问题

### ISSUE THREAD

**Issue by huwan** [tgbot-collection/SearchGram#86]
感谢开发SearchGram，使用Docker 成功部署了SearchGram，并且搜索可以正常使用。但是过了大概一周时间后，搜索非常慢，使用`/ping`命令发现数据库已经超过1GB大小了，索引接近8万条记录。

```
Pong!
Index telegram has 79799 documents

Database size: 1.2GiB
Last update: 2023-04-08T07:13:22.72765123Z
```
我有几十上百个群组和频道，但是只想同步一个聊天群和几个朋友的对话，为此我设置了`sync.ini`文件，里面只填写了一个群组和几个朋友的ID，想只搜索这些聊天记录。ignore列表设置为空。
```
[chat]
-10018xxxxxxxx
546xxxxxxx
566xxxxxxx
565xxxxxxx
[ignore]
```
但是测试发现，搜索结果里面出现了白名单之外的记录。请教是否是我设置的问题，是否可以只同步chat字段下面的记录，默认忽略所有其它聊天记录呢？谢谢。

**Comment by Potat0000** [comment]
`chat` 为“将这些人/群组的所有聊天记录全部同步到数据库中，即使这些聊天是在启动 SearchGram 之前产生的”，也就是一个同步的功能。

但是我也同意在 `ignore` 的黑名单之外添加白名单机制。TG 的无关群聊确实很多。

**Comment by Potat0000** [comment]
> `chat` 为“将这些人/群组的所有聊天记录全部同步到数据库中，即使这些聊天是在启动 SearchGram 之前产生的”，也就是一个同步的功能。
> 
> 但是我也同意在 `ignore` 的黑名单之外添加白名单机制。TG 的无关群聊确实很多。

如果增加白名单，则建议在 `sync.ini` 之外创建 `chatlist.ini` 配置文件，使用 `[whitelist]` 和 `[blacklist]` 进行控制，以避免原 Issue 的歧义。

**Comment by BennyThink** [comment]
楼上说的对，`chat`是同步，`ignore`是黑名单，白名单的机制还没有。

**Comment by BennyThink** [comment]
如果配置文件最终格式是
```
[sync]
; 同步历史消息，使用ID、username

[blacklist]
; 不同步，使用ID、username或者chat type如BOT、PRIVATE

[whitelist]
; 同步
```
这样感觉如何？

**Comment by huwan** [comment]
感谢～配置文件写在一个配置文件或者两个不同的文件都可以，我没有意见。

我部署用的机器是一台性能很弱的小机器。并且之前以为是只索引了几个聊天记录，搜索时没有加限定群组或者用户的选项和参数，导致部分命中匹配出来的结果高达上千条，要花好多时间。后面有黑白名单之后很弱的机器应该也没问题啦;-)

**Comment by BennyThink** [comment]
嗷我懂了，可能meilisearch对内存的需求还是挺高的……
