### ISSUE TITLE
请问怎样选择是否模糊搜索呢

### ISSUE THREAD

**Issue by Monkey2003** [tgbot-collection/SearchGram#94]

**Comment by BennyThink** [comment]
似乎没办法选择，等会我看看meilisearch 文档，也许有解决方案

**Comment by BennyThink** [comment]
<img width="603" alt="iShot_2023-05-02_20 32 24" src="https://user-images.githubusercontent.com/14024832/235755239-3b4e903a-da6a-47af-ad09-86f9a1cec253.png">

可以了
