### ISSUE TITLE
结果排序，命令格式，黑白名单优先级

### ISSUE THREAD

**Issue by bennyzdog** [tgbot-collection/SearchGram#97]
- [x] . 搜索结果不是完全按照时间顺序排列的，影响使用

- [x]  `-t=GROUP -u=user_id|username keyword`

    可以直接改成 `/group keyword`，简化格式，也方便使用命令菜单自动补全。同理其它类型的聊天也可做成命令，用户也可以 `/user userid|username kyword`

- [x] 黑名单和白名单的优先级，目前是黑名单优先级更高，这产生一个问题：如果我不想同步群组消息，但针对个别群组需要放行，黑名单在前则无法实现。

建议改成白名单优先级更高，或者可以由用户自行决定（例如根据配置的顺序，越靠下/上的优先级越高）

**Comment by BennyThink** [comment]
```md
/bot - Search messages from bots
/channel - Search messages from channels
/group - Search messages from groups
/private - Search messages from private chats
/supergroup - Search messages from supergroups
```

**Comment by bennyzdog** [comment]
时间排序还有问题。
只修复了同一页的结果的顺序错乱，但全部搜索结果（分页）时上一页最后一条并不是接着下一页第一条的

**Comment by bennyzdog** [comment]
`-u=user_id|username keyword` 也可优化，与 `/type` 命令进行合并，从而简化搜索体验

当命令为 `/type key1 key2` 时，识别 key1 为用户名，key2 为 keyword
当命令为 `/type key1` 时，识别 key1 为 keyword

**Comment by bennyzdog** [comment]
`/help` 返回的信息没有更新

**Comment by bennyzdog** [comment]
命令可以优化，当用户只发送命令，不带后面的 key，提示用户重发正确的格式

> ```lisp
> /bot - Search messages from bots
> /channel - Search messages from channels
> /group - Search messages from groups
> /private - Search messages from private chats
> /supergroup - Search messages from supergroups
> ```

**Comment by BennyThink** [comment]
全修好了！

**Comment by Potat0000** [comment]
时间好像还是有问题。
![1](https://github.com/tgbot-collection/SearchGram/assets/11223244/409c7b1c-f28c-44b8-865d-1b12846fc058)

把前三页的时间单独拿出来是这样的：
```
Page1:
2023-04-28 14:26:31
2023-04-23 22:10:20
2023-04-23 22:10:04
2023-04-23 21:01:58
2023-04-23 13:13:01
2023-04-16 23:43:51
2023-04-16 14:04:09
2023-04-14 20:04:11
2023-04-14 18:57:10
2023-04-12 20:57:40

Page2:
2023-03-08 11:52:59
2022-12-20 12:22:22
2023-05-21 13:01:50
2023-05-20 14:09:39
2023-05-17 13:08:25
2023-05-07 13:16:59
2023-04-28 16:38:42
2023-04-28 14:32:17
2023-04-27 23:33:15
2023-04-23 22:12:18

Page3:
2023-04-23 22:11:55
2023-04-23 22:11:13
2023-04-23 22:10:25
2023-04-23 22:09:27
2023-04-23 22:06:26
2023-04-21 16:39:13
2023-04-20 22:08:54
2023-04-12 21:24:35
2023-04-09 21:51:37
2023-03-15 11:56:51
```

观察了一下，似乎后半部分是对的，第一页和第二页开头的部分是错的。

是否应该考虑一下 sync 的时间戳、正常读取的时间戳、add_timestamp 的时间戳里是不是有哪个出了问题？

**Comment by BennyThink** [comment]
🫠 已经跑完了 `add_timestamp` 吗？所有的数据都有对应的时间戳了？

**Comment by Potat0000** [comment]
> 🫠 已经跑完了 `add_timestamp` 吗？所有的数据都有对应的时间戳了？

跑完了的，在 meilisearch 面板里都有 `TIMESTAMP` 的。

刚刚往后面多翻了几页，后面还是乱的，并不是只有第一页第二页有问题

**Comment by BennyThink** [comment]
🫠 好，那可能是排序的bug，我周末抽空看一下

**Comment by BennyThink** [comment]
好像是meilisearch 的bug...

**Comment by BennyThink** [comment]
解决了，是ranking rule的问题 https://www.meilisearch.com/docs/reference/api/settings#update-ranking-rules

重新拉image，然后重启下就应该好了

**Comment by BennyThink** [comment]
我测了一下可以了

**Comment by Potat0000** [comment]
> 我测了一下可以了

已经修复了。十分感谢！
