### ISSUE TITLE
关于搜索结果

### ISSUE THREAD

**Issue by suikaremilia** [tgbot-collection/SearchGram#99]
您好，SearchGram很实用，有个关于搜索结果的小建议：
点击搜索结果的消息内容会复制消息文本，但为什么不是直接重定向到原消息会话呢？
返回到原消息会话，可以方便的在上面进行回复或复制，感觉这样比直接复制消息文本实用性更强一些。
目前这样的返回结果还得手动去找会话，定位日期和时间，再进行回复，有点麻烦。

**Comment by BennyThink** [comment]
Telegram 有URI scheme，但是对于私聊，没办法直接定位到具体的消息（公开频道和群组可以），最多能做到的事情就是定位到当初聊天的那个人。你指的是添加这个功能吗？

**Comment by suikaremilia** [comment]
是的，我是觉得目前搜索结果点击复制的功能比较鸡肋，可以更丰富一些，但抱歉我没看过tg的文档不知道URI scheme对私聊还有这个限制。

**Comment by BennyThink** [comment]
👌  那可能最多能做的事情就是点击对方的名字，跳转到对应的对话。这个改天我加一下
